version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:3000
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    restart: always
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: [ "npm", "run", "test" ]
